### ISSUE TITLE
Suspicious literal dead link

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/js-x-ray#166]
https://github.com/NodeSecure/js-x-ray/blob/c3caab9d13e44b1d50abae3b90118a8fc6709802/docs/suspicious-literal.md?plain=1#L9

[smith-and-wesson-skimmer](https://badjs.org/posts/smith-and-wesson-skimmer/)

**Comment by jean-michelet** [comment]
Do you want to remove the reference or looking for a new one?

**Comment by PierreDemailly** [comment]
Ideally a new one imo.
The only one reference for Smith & Wesson I found is https://sansec.io/research/magecart-hackers-target-sanguine. There are others but they are not focused on JS.
There are also probably good articles that does not ref the S&W skimmer, examples:
- https://isc.sans.edu/diary/Interesting+JavaScript+Obfuscation+Example/25020
- https://www.zscaler.fr/blogs/security-research/de-obfuscating-dom-based-javascript-obfuscation-found-eks-such-fiesta-and-rig

Here is the [original link on Web Archive](https://web.archive.org/web/20200804103413/https://badjs.org/posts/smith-and-wesson-skimmer/)

@fraxken Does any of theses links feel good to you ?

**Comment by fraxken** [comment]
@PierreDemailly We can put the webarchive one I think
