### ISSUE TITLE
fs-constants@1.0.0 index.js detected as minified

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#168]
The following file is detected as minified: https://unpkg.com/fs-constants@1.0.0/index.js

expected: should not be detected as a minified file

**Comment by jean-michelet** [comment]
Looking into it.

**Comment by jean-michelet** [comment]
It comes from the library `is-minified-code`...

I logged here: https://github.com/NodeSecure/js-x-ray/blob/527319006e2b0ef337bde04bee8f7345585b63d4/index.js#L67

I think one line file expressions are considered minified by default.

Considered minified:
```js
module.exports = require('fs').constants || require('constants')
```

Considered NOT minified:
```js
module.exports = require('fs').constants 
|| require('constants')
```

Why is it a big deal?

**Comment by fraxken** [comment]
@jean-michelet Nothing crazy, it just report the file as minified when not in the CLI (false positive).

Yes is-minified-code is not perfect, last time @PierreDemailly was sharing another package but it has downside too.

**Comment by PierreDemailly** [comment]
Yeah, didn't find a more accurate lib unfortunately.
May we could check for a minimum length if the file is one line ? Something like `isMinified(str) && (str.split(/\r?\n/).length > 1 ? true : str.length > 200)` ?
