### ISSUE TITLE
minimatch@9.0.3 cjs/index.js detected as obfuscated code "morse"

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#170]
https://unpkg.com/minimatch@9.0.3/dist/cjs/index.js

**Comment by jean-michelet** [comment]
Looking into it...

**Comment by jean-michelet** [comment]
I'm not sure there's anything trivial to do here, the lib has functions that concatenate a lot of strings such as `'.'` and `'..'` and there are too many of them (46): https://github.com/NodeSecure/js-x-ray/blob/527319006e2b0ef337bde04bee8f7345585b63d4/src/obfuscators/index.js#L23

I guess people will have to decide for themselves whether to ignore the errors in this library or use another one?
