### ISSUE TITLE
evaluate path.join for require?

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#178]
The aim would be to successfully resolve dependency paths like in the following code example;

```js
const bin = require(path.join('.', 'bin.js'))
```

For this given code we want:
- Normalized dependency with `./bin.js` path (normalized using UNIX path)
- No unsafe-import warning

There is possibility for having identifiers like `__dirname` to appear

```js
const bin = require(path.join(__dirname, 'bin.js'))
```

The challenge here is to compute the location of the file to dynamically inject the `__dirname` value (Maybe to handle in a second evolution).

**Comment by fraxken** [comment]
@jean-michelet yes

**Comment by jean-michelet** [comment]
Looking into it @fraxken
