### ISSUE TITLE
Properly detect eval("require") as require

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#179]
https://unpkg.com/file-type@16.5.4/core.js

We should detect the following code as an unsafe-import (but still detect the usage of the `stream` core module)

```js
// Using `eval` to work around issues when bundling with Webpack
const stream = eval('require')('stream'); // eslint-disable-line no-eval
```

**Comment by fabnguess** [comment]
@fraxken, I can't find the instruction `const stream = eval('require')('stream')` anywhere in the source code. Could you please guide me?
