### ISSUE TITLE
Should we add "trojan-source" code detection?

### ISSUE THREAD

**Issue by mbalabash** [NodeSecure/js-x-ray#19]
Hey!

There are a paper about ["trojan-source" attack](https://trojansource.codes/) and [tool](https://github.com/lirantal/anti-trojan-source#use-as-a-library) for detecting it.

Should we add a new warning for this attack? 

If so, I can prepare PR for it.

**Comment by fraxken** [comment]
Hello 👋,

This has already been implemented few months ago: https://github.com/NodeSecure/js-x-ray/pull/16

**Comment by mbalabash** [comment]
Awesome! 
I haven’t seen it.
