### ISSUE TITLE
Refactor isRequire probe

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#220]
The idea/goal of the task is to refactor the isRequire who is becoming more complicated to read and maintain.

I think the part where we walk the require arguments need to be externalized to a dedicated class: https://github.com/NodeSecure/js-x-ray/blob/master/src/probes/isRequire.js#L142

However this can be a challenge because of how we currently walk the AST.

**Comment by jean-michelet** [comment]
I'm gonna work on it.
