### ISSUE TITLE
Refactor analysis variable to sourceFile

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#224]
The codebase contains a lot of `analysis` variable which is the old name of SourceFile class.

https://github.com/search?q=repo%3ANodeSecure%2Fjs-x-ray%20analysis&type=code

We should rename it `sourceFile` to avoid confusion.

**Comment by FredGuiou** [comment]
I take it, if you agree, you can assign me ! 👍🏻
