### ISSUE TITLE
Migrate estree-ast-utils from tape to test_runner

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/js-x-ray#225]
Exemple PR https://github.com/NodeSecure/js-x-ray/pull/108

**Comment by FredGuiou** [comment]
@PierreDemailly Could you assign it to me ? I'm gonna try to complete this issue. 🤓

**Comment by jean-michelet** [comment]
I don't think you should worry about being assigned @FredGuiou, because we know who you are.
Imo, just tell us you want to fix it and go for it :+1 :
