### ISSUE TITLE
Detect URL with IPs as unsafe-link

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#256]
URL with raw IPs should be tagged as unsafe links (except 127.0.0.1).

See the following code: https://unpkg.com/browse/u-workflow.auth@2.0.0/index.js (do not use this as example, this code is dangerous)

**Comment by sairuss7** [comment]
Hi Thomas can you please assign me this issue? Please. Thanks.

**Comment by jean-michelet** [comment]
Package was removed, you can still see the code here: https://socket.dev/npm/package/u-workflow.auth/files/2.0.0/index.js#T221-228

Example of dangerous pattern:
```
var url = "http://77.244.210.247/burpcollaborator.txt";
```
