### ISSUE TITLE
Add a severity property to warnings

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#26]
As time goes by, I think that not all warnings are equivalent.

I want to add a new severity property for each warning:

- Information (For things not related to security, with valid values or a lot of false positive).
- Warning (the default).
- Critical (Implies malicious code or intent).

> Maybe the way we call them is not right ? Maybe we should call warning "Alarm" ?

---

I will classify the existing warnings this way:

- Information: `parsing-error`, `encoded-literal`
- Warning: **ALL OTHERS**
- Critical: `obfuscated-code`

**Comment by Mathieuka** [comment]
I'm in ☝🏼 🙂
