### ISSUE TITLE
[AstAnalyser API] Implement analyseFileSync

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#265]
The idea is to implement a synchronous version of `analyseFile` to simply scenarios where we don't need an Asynchronous I/O. Recent API updates would force to switch some sync API to async (requiring ESM and Top-level-await).

**Comment by FredGuiou** [comment]
I take it 🚀

**Comment by FredGuiou** [comment]
https://github.com/NodeSecure/js-x-ray/pull/275

@fraxken , @PierreDemailly 🚀
