### ISSUE TITLE
Add deprecation warning to runASTAnalysis and runASTAnalysisOnFile

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#266]
Add a deprecation warning to our legacy API `runASTAnalysis` and `runASTAnalysisOnFile` to detect and force people still using them to upgrade. We could easily do that using Node.js `process.emitWarning` API.

An example message could be `The runASTAnalysis API is deprecated and will be removed in v8. Please use the AstAnalyser class instead.`

**Comment by fless-lab** [comment]
Hello @fraxken 

Can i solve this issue ?
