### ISSUE TITLE
New npmjs.com Release?

### ISSUE THREAD

**Issue by cccs-kevin** [NodeSecure/js-x-ray#52]
Hey NodeSecure,

We at the [@CybercentreCanada](https://github.com/CybercentreCanada) love JS-X-Ray and have it tightly integrated into our JavaScript analysis service [JsJaws](https://github.com/CybercentreCanada/assemblyline-service-jsjaws). However, it looks like there is work being done on this project that has not been released to npmjs.com? The release version [there ](https://www.npmjs.com/package/js-x-ray ) is 3.2.0 but it looks like you are on [v5.1.0](https://github.com/NodeSecure/js-x-ray/releases/tag/v5.1.0). Any chance you can update this on npmjs.com?

🇨🇦

**Comment by Kawacrepe** [comment]
Hey @cccs-kevin

I supposed you were using the following package https://www.npmjs.com/package/js-x-ray

We currently release it under the @nodesecure scope, with the others project you can find on this organization https://www.npmjs.com/package/@nodesecure/js-x-ray

Do it answer your problem ?

**Comment by antoine-coulon** [comment]
@NodeSecure/core we should probably mention this in the former `js-x-ray` package so that people are more easily informed that the package is now maintained under the `@nodesecure` scope

**Comment by fraxken** [comment]
Just deprecated the old package
![image](https://user-images.githubusercontent.com/4438263/196394015-893e2a34-2d62-4906-bc22-9ab8123fb971.png)

**Comment by cccs-kevin** [comment]
Perfect thank you everyone!
